#!/usr/bin/env bash
set -euo pipefail


readonly -A setting=(
	[plot-vert-padding]=0.1
	[plot-candlestick-neg-color]='red'
	[plot-candlestick-pos-color]='green'
	[ema-weight]=0.8
	[csv-separator]=','
)

readonly -A csvcol=(
	[id]=1
	[date]=2
	[open]=3
	[high]=4
	[low]=5
	[close]=6
	[volume]=7
	[ema]=3
)

readonly -A error=(
	[bad-args]=101
	[bad-cmd]=102
)


apikey()
{
	local key="${1}"
	local -A uid=(
		[alphavantage.co]="co/alphavantage/x@wilsonb.com/api-key"
	)

	pass show "${uid[${key}]}"
}


## Fetch and postprocess CSV data from alphavantage.co
#
# @param <1>  Stock symbol
# @param [2]  Function
# @param [3]  Output size
# @param [4]  Interval
# @param [5]  CSV separator
fetch_csv_time_series_alphavantage_co()
{
	local apikey
	local symbol="${1}"
	local function="${2-default}"
	local outputsize="${3-default}"
	local interval="${4-default}"
	local sep="${5-${setting[csv-separator]}}"
	apikey="$(apikey alphavantage.co)"

	fetch_time_series_alphavantage_co "${apikey}" \
	                                  "${symbol}" \
	                                  "${function}" \
	                                  "${outputsize}" \
	                                  "${interval}" \
	                                  csv \
	| postfetch_csv_alphavantage_co_time_series "${sep}"
}

## Fetch JSON data from alphavantage.co
#
# @param <1>  API key
# @param <2>  Stock symbol
# @param [3]  Function
# @param [4]  Output size
# @param [5]  Interval
# @param [6]  Datatype
# @stdout     JSON result
fetch_time_series_alphavantage_co()
{
	[[ ${#} -lt 2 ]] && return "${error[bad-args]}"
	[[ -z "${1}" ]] && return "${error[bad-args]}"
	[[ -z "${2}" ]] && return "${error[bad-args]}"

	local url='https://www.alphavantage.co'
	local path="query"
	local query=""

	local -A function=(
		[intraday]='TIME_SERIES_INTRADAY'
		[daily]='TIME_SERIES_DAILY'
		[daily-adjusted]='TIME_SERIES_DAILY_ADJUSTED'
		[weekly]='TIME_SERIES_WEEKLY'
		[monthly]='TIME_SERIES_MONTHLY'
		[default]="${function[daily]}"
	)
	local -A outputsize=(
		[compact]='compact'
		[full]='full'
		[default]="${outputsize[compact]}"
	)
	local -A interval=(
		[1min]='1min'
		[5min]='5min'
		[15min]='15min'
		[30min]='30min'
		[60min]='60min'
		[default]="${interval[60min]}"
	)
	local -A datatype=(
		[json]='json'
		[csv]='csv'
		[default]="${datatype[json]}"
	)

	local -A field=(
	        [apikey]="${1}"
		[symbol]="${2}"
	        [function]="${function[${3-default}]}"
	        [outputsize]="${outputsize[${4-default}]}"
	        [interval]="${interval[${5-default}]}"
	        [datatype]="${datatype[${6-default}]}"
	)

	for f in "${!field[@]}"; do
		query+="&${f}=${field[${f}]}"
	done
	query="${query#&}"

	curl --silent "${url}/${path}?${query}"
}

## Vendor-independent function for fetching data
fetch_csv_time_series()
{
	fetch_csv_time_series_alphavantage_co "${@}"
}

## Postprocess alphavantage.co CSV result
#
# @param [1]  CSV separator
postfetch_csv_alphavantage_co_time_series()
{
	local sep="${1-${setting[csv-separator]}}"
	IFS= read -r

	sed "s/\\r$//;
	     s/,/${sep}/g" \
	| nl --number-width=1 --number-separator=','
}

## Prepend metadata header to TSV data
#
# @param <1>  Column that contains data minimum
# @param <2>  Column that contains data maximum 
# @param [3]  CSV separator
munge_csv_prepend_header()
{
	local mincol="${1}"
	local maxcol="${2}"
	local sep="${3-${setting[csv-separator]}}"
	local low high range count
	local dat=""

	low=$(getconf INT_MAX)
	high=$(getconf INT_MIN)

	while IFS= read -r l; do
		local llow
		local lhigh

		llow=$(echo "${l}"  | cut -d"${sep}" -f"${mincol}")
		lhigh=$(echo "${l}" | cut -d"${sep}" -f"${maxcol}")

		if [[ $(bc <<<"${llow} < ${low}") -eq 1 ]]; then
			low=${llow}
		fi
		if [[ $(bc <<<"${lhigh} > ${high}") -eq 1 ]]; then
			high=${lhigh}
		fi

		dat="$(echo -e "${dat}\n${l}")"
	done

	range=$(bc <<<"${high} - ${low}")
	count=$(tail -1 <<<"${dat}" | cut -d"${sep}" -f1)

	echo "${high}" "${low}" "${range}" "${count}"
	echo "${dat}"
}

## Generate EMA column(s) from input column
#
# @param <1>  Exponential weight
# @param [3]  CSV separator
munge_csv_ema()
{
	local weight="${1}"
	local sep="${2-${setting[csv-separator]}}"

	if [[ $(bc <<<"${weight} <  0") -eq 1 ]] \
	|| [[ $(bc <<<"${weight} >  1") -eq 1 ]]; then
		return "${error[bad-arg]}"
	fi

	local id date open high low sum volume
	IFS="${sep}" read -r id date open high low sum volume
	echo -e "${id}${sep}${date}${sep}${sum}"

	local meas=1
	while IFS="${sep}" read -r id date open high low close volume; do
		local ema

		meas=$(bc <<<"${meas}*${weight} + 1")
		sum=$(bc <<<"${sum}*${weight} + ${close}")
		ema=$(bc <<<"${sum}/${meas}")

		echo -e "${id}${sep}${date}${sep}${ema}"
	done
}


## Colorized candlestick plot in X11
#
# @param [1]  Color for losses
# @param [2]  Color for gains
# @param [3]  Fraction of visual padding on top and bottom of graph
# @param [4]  CSV separator
plot_candlestick()
{
	local negcolor="${1-red}"
	local poscolor="${2-green}"
	local pad="${3-0}"
	local sep="${4-${setting[csv-separator]}}"
	local negval=-1
	local posval=1
	local high low range count
	local xmin xmax ymin ymax
	IFS=" " read -r high low range count
	IFS= read -r

	xmin=0
	xmax=$(( count + 1 ))
	ymin=$(bc <<<"${low}  - ${range} * ${pad}")
	ymax=$(bc <<<"${high} + ${range} * ${pad}")

	gnuplot --persist -e "
		set datafile separator '${sep}';

		set xrange [${xmin}:${xmax}];
		set yrange [${ymin}:${ymax}];

		set palette defined ( ${negval} '${negcolor}'
		                    , ${posval} '${poscolor}' );
		set cbrange [${negval}:${posval}];
		unset colorbox;
		set style fill solid noborder;

		plot '<cat' using ${csvcol[id]}
		                  :${csvcol[open]}
		                  :${csvcol[low]}
		                  :${csvcol[high]}
		                  :${csvcol[close]}
		                  :(\$${csvcol[close]} < \$${csvcol[open]}
		                    ? ${negval}
		                    : ${posval})
		            with candlesticks
		            palette
		            notitle;
	"
}

## ASCII line plot
#
# Draw an ASCII line plot. Defaults to closing prices from standard TSV
#
# @param [1]  Plot x-axis column
# @param [2]  Plot y-axis column
# @param [3]  Fraction of visual padding on top and bottom of graph
# @param [3]  CSV separator
plot_linespoints()
{
	local xcol=${1-${csvcol[id]}}
	local ycol=${2-${csvcol[close]}}
	local pad="${3-0}"
	local sep="${4-${setting[csv-separator]}}"
	local high low range count
	local xmin xmax ymin ymax
	IFS=" " read -r high low range count
	IFS= read -r

	xmin=0
	xmax=$(( count + 1 ))
	ymin=$(bc <<<"${low}  - ${range} * ${pad}")
	ymax=$(bc <<<"${high} + ${range} * ${pad}")

	gnuplot --persist -e "
		set datafile separator '${sep}';

		set xrange [${xmin}:${xmax}];
		set yrange [${ymin}:${ymax}];

		plot '<cat' using ${xcol} : ${ycol}
		            with linespoints
		            notitle;
	"
}


cmd_candle()
{
	fetch_csv_time_series "${@}" \
	| munge_csv_prepend_header "${csvcol[low]}" "${csvcol[high]}" \
	| plot_candlestick "${setting[plot-candlestick-neg-color]}" \
	                   "${setting[plot-candlestick-pos-color]}" \
	                   "${setting[plot-vert-padding]}"
}

cmd_ema()
{
	fetch_csv_time_series "${@}" \
	| munge_csv_ema "${setting[ema-weight]}" \
	| munge_csv_prepend_header "${csvcol[ema]}" "${csvcol[ema]}" \
	| plot_linespoints "${csvcol[id]}" "${csvcol[ema]}" \
	                   "${setting[plot-vert-padding]}"
}

usage()
{
	cat <<- EOF
	Usage: ${0} <security symbol>
	EOF
}


main()
{
	if [[ ${#} -eq 0 ]]; then
		usage
		return "${error[bad-cmd]}"
	fi

	readonly cmd="${1}"
	shift

	case "${cmd}" in
		candle) cmd_candle "${@}";;
		ema)    cmd_ema "${@}";;
		_debug) "${@}";;
		*) usage;;
	esac
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
	main "${@}"
fi
