#! /usr/bin/env sh

function __init(){
### Module Start

function print_usage()
{
  cat <<EOF
Usage: ${0} <DEVICE PATH>

${0} wipes <DEVICE PATH> with bytes from /dev/urandom. Since write access to
<DEVICE PATH> is required, typically this will be run with sudo.

A progress bar tracks the status of the write.
EOF
}

function check_args()
{
  if [[ ${#} -eq 0 ]]; then
    echo "Error: Expected <DEVICE PATH>"
    echo
    print_usage
    exit
  elif [[ ! -b ${1} ]]; then
    echo "Error: ${1} does not exist or is not a block device."
    exit
  fi
}

function wipe()
{
  local DEV=${1}
  local NUM_BLOCKS=$(fdisk -l ${DEV} | grep 'sectors$' | cut -d' ' -f7)
  local BLOCK_SIZE=$(fdisk -l ${DEV} | grep '^Sector size' | cut -d' ' -f4)
  local DISK_SIZE=$(fdisk -l ${DEV} | grep "^Disk ${DEV}" | cut -d' ' -f5)

  openssl enc -aes-256-ctr \
    -pass pass:"$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" \
    -nosalt </dev/zero \
    | pv -bartpes ${DISK_SIZE} | dd bs=${BLOCK_SIZE} \
                                    count=${NUM_BLOCKS} \
                                    of=${DEV}
}

function main()
{
  check_args ${@}
  wipe ${@}
}

main ${@}

### Module End
}
__init ${@}
[[ -n $(typeset -f __init) ]] && unset -f __init
