#!/usr/bin/env sh
set -o errexit -o nounset -o noclobber


_cp() { cp ${VERBOSE+--verbose} "${@}"; }
_mkdir() { mkdir ${VERBOSE+--verbose} --parents "${@}"; }

usage() {
	cat <<-USAGE
	Usage: $(basename "${0}") [-x] <newroot> [<command>]
	The default <command> is \$SHELL, currently set to ${SHELL}.
	USAGE
}

fail() {
	msg=${1}
	errno=${2-1}

	>&2 echo "ERROR: ${msg}"
	>&2 echo
	>&2 usage
	exit "${errno}"
}


setup_net() {
	vroot=${1}
	_cp /etc/resolv.conf "${vroot}/etc/"
}

setup_dirs() {
	vroot=${1}
	_mkdir "${vroot}/proc"
	_mkdir "${vroot}/sys"
	_mkdir "${vroot}/dev"
	_mkdir "${vroot}/run"
	_mkdir "${vroot}/tmp/.X11-unix"
}

setup_x11() {
	vroot=${1}

	xauth list "${DISPLAY}" \
	| cut --fields=1 --delimiter=' ' \
	| xargs xauth extract - \
	| xauth -f "${vroot}/tmp/.Xauthority" merge -
}

uunshare() {
	vroot=${1}; shift

	env --ignore-environment -- \
		TERM="${TERM}" \
		${share_x11+DISPLAY="${DISPLAY}"} \
		${share_x11+XAUTHORITY='/tmp/.Xauthority'} \
		xbps-uunshare \
			-b /proc:proc \
			-b /sys:sys \
			-b /dev:dev \
			-b /run:run \
			${share_x11+-b /tmp/.X11-unix:tmp/.X11-unix} \
			-- "${vroot}" "${@}"
}


while getopts ':m:hx' opt "${@}"; do
	case "${opt}" in
		h) usage; exit;;
		x) share_x11=1;;
		:) fail "Missing option argument: -${OPTARG}";;
		*) fail "Unrecognized option: -${OPTARG}";;
	esac
done
shift $((OPTIND - 1))


[ "${#}" -gt 0 ] || fail "Missing arguments"

vroot=${1}; shift
[ -d "${vroot}" ] || fail "Unable to find vroot ${vroot}"

setup_net "${vroot}"
setup_dirs "${vroot}"
[ "${share_x11:-}" ] && setup_x11 "${vroot}"
uunshare "${vroot}" "${@:-${SHELL}}"
