#! /usr/bin/env sh

_which()
{
	which "${1}" 2>/dev/null
}

print_usage()
{
cat <<EOF
Usage: ${0} <DEVICE PATH>

${0} wipes <DEVICE PATH> with bytes from /dev/urandom. Since write access to
<DEVICE PATH> is required, typically this will be run with sudo.

A progress bar tracks the status of the write.
EOF
}

check_deps()
{
	for dep in pv dd; do
		if [ ! -x "$(_which ${dep})" ]; then
			echo "ERROR: Could not find program ${dep}"
			exit
		fi
	done
}

check_args()
{
	if [ ${#} -eq 0 ]; then
		echo "Error: Expected <DEVICE PATH>"
		echo
		print_usage
		exit
	elif [ ! -b ${1} ]; then
		echo "Error: ${1} does not exist or is not a block device."
		exit
	fi
}

wipe()
{
	local dev=${1}
	local nsecs=$(fdisk -l ${dev} | grep 'sectors$' | cut -d' ' -f7)
	local secsz=$(fdisk -l ${dev} | grep '^Sector size' | cut -d' ' -f4)
	local disksz=$(fdisk -l ${dev} | grep "^Disk ${dev}" | cut -d' ' -f5)

	</dev/urandom pv --bytes \
	   --average-rate        \
	   --rate                \
	   --timer               \
	   --progress            \
	   -eta                  \
	   --size ${disksz}      \
	| dd bs=${secsz}         \
	     count=${nsecs}      \
	     of=${dev}
}

check_args ${@}
check_deps
wipe ${@}
