#!/usr/bin/env sh

BROW_KEY_REFRESH="r"

echo "Click on browser window"
BROW_WIN=$(xwininfo | awk '/Window id/{print $4}')

echo "Click on terminal window"
TERM_WIN=$(xwininfo | awk '/Window id/{print $4}')

while true; do
	INOTIFY_OUT=$(inotifywait -e modify,attrib,move,create,delete $@)
	echo ${INOTIFY_OUT}
	if [[ -n "${INOTIFY_OUT}" ]]; then
		xdotool windowactivate ${BROW_WIN}
		xdotool key ${BROW_KEY_REFRESH}
		xdotool windowactivate ${TERM_WIN}
	fi
done
